### ISSUE TITLE
How to buy MID360 lidar？

### ISSUE THREAD

**Issue by zhuhu00** [ZiliangMiao/Hybrid_Mapping_Cocalibration#1]
There is no purchase link for the device on the official website.

**Comment by ZiliangMiao** [comment]
Livox Technology has already released this novel LiDAR, please refer to https://www.livoxtech.com/cn/mid-360

**Comment by zhuhu00** [comment]
Thanks.
> Livox Technology has already released this novel LiDAR, please refer to https://www.livoxtech.com/cn/mid-360
