### ISSUE TITLE
what is configuration  of fisheye camera 

### ISSUE THREAD

**Issue by wlt027** [ZiliangMiao/Hybrid_Mapping_Cocalibration#2]
Hi,thank you for your work!
Can you share your camera configuration?

**Comment by ZiliangMiao** [comment]
It's an omnidirectional camera (an unreleased prototype version) with 2048x2448 pixels, refer to Huanjun Technology (panoholic) for more details.

**Comment by wlt027** [comment]
This project includs a MindVision SDK for camera.Is it a mindvision camera and omnidectional lens

**Comment by wlt027** [comment]
Can you share more details about this camera? Is it a MindVision camera with a panorama lens from Huanjun Technology?
How to contact them？I am very interested in this camera.

**Comment by ZiliangMiao** [comment]
It is a Mindvision camera with a panorama lens, please contact bai@zju.edu.cn
