### ISSUE TITLE
Could you provide your experimental data?

### ISSUE THREAD

**Issue by Eserda0114** [ZiliangMiao/Hybrid_Mapping_Cocalibration#3]
Thank you for your open source!
Your work looks exciting，but I couldn't run it correctly.
Could you provide your experimental data? 
Does it only need a pcd file and a bmp file to run？

**Comment by ZiliangMiao** [comment]
Thanks for your interest. The co-calibration module only requires a .pcd file and a .bmp file to run. I will pose a link to our example dataset later.

**Comment by ZiliangMiao** [comment]
The example dataset has been uploaded through Google drive, https://drive.google.com/file/d/13jmpb2Ft_-LXh990wIxUrSLnYEimYKsa/view?usp=share_link

**Comment by Eserda0114** [comment]
Thank you for your open source dataset！👍🤝
